repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.28.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: '0.26'
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
    - id: zizmor
